import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    projects: [
      "packages/shared",
      "packages/skills-catalog",
      "packages/mcp-server",
      "packages/db",
      "packages/adapter-utils",
      "packages/adapters/acpx-local",
      "packages/adapters/claude-local",
      "packages/adapters/codex-local",
      "packages/adapters/cursor-cloud",
      "packages/adapters/cursor-local",
      "packages/adapters/gemini-local",
      "packages/adapters/grok-local",
      "packages/adapters/openclaw-gateway",
      "packages/adapters/opencode-local",
      "packages/adapters/pi-local",
      "packages/plugins/sdk",
      "packages/plugins/create-paperclip-plugin",
      "packages/plugins/plugin-llm-wiki",
      "packages/plugins/plugin-workspace-diff",
      "packages/plugins/paperclip-plugin-fake-sandbox",
      "packages/plugins/examples/plugin-authoring-smoke-example",
      "packages/plugins/examples/plugin-kitchen-sink-example",
      "packages/plugins/examples/plugin-orchestration-smoke-example",
      "packages/plugins/sandbox-providers/cloudflare",
      "packages/plugins/sandbox-providers/cloudflare/bridge-template",
      "packages/plugins/sandbox-providers/daytona",
      "packages/plugins/sandbox-providers/e2b",
      "packages/plugins/sandbox-providers/exe-dev",
      "packages/plugins/sandbox-providers/modal",
      "server",
      "ui",
      "cli",
    ],
  },
});
